# Generated by Django 6.1.1 on 2026-10-05 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_status'),
        ('orders', '0003_order_stock_reserved'),
    ]

    operations = [
    ]
