# Generated by Django 6.1.1
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    initial = True
    dependencies = [('orders', '0001_initial')]
    operations = [migrations.CreateModel(name='Payment', fields=[
        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        ('gateway', models.CharField(default='razorpay', max_length=30)),
        ('gateway_order_id', models.CharField(max_length=100, unique=True)),
        ('gateway_payment_id', models.CharField(blank=True, max_length=100)),
        ('status', models.CharField(choices=[('created','Created'),('authorized','Authorized'),('captured','Captured'),('failed','Failed'),('refunded','Refunded')], default='created', max_length=30)),
        ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
        ('currency', models.CharField(default='INR', max_length=3)),
        ('raw_response', models.JSONField(blank=True, default=dict)),
        ('created_at', models.DateTimeField(auto_now_add=True)),
        ('updated_at', models.DateTimeField(auto_now=True)),
        ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order')),
    ])]
